[build]
publish = "dist"
command = '''
set -e
npm run build
cp .env.production .env
echo -e "APP_URL=http://127.0.0.1:8000" >> .env
echo -e "JOCKO_API_KEY=$JOCKO_API_KEY" >> .env
php artisan key:generate
php -S 127.0.0.1:8000 public/index.php & pid=$!
sleep 1
php artisan export || cat ./storage/logs/laravel.log && EXIT_STATUS=1
echo "killing server (process id '$pid')"
kill $pid
exit $EXIT_STATUS
'''
environment = { PHP_VERSION = "8.1" }
