[build]
publish = "dist"
command = '''
    npm run build &&
    cp .env.production .env &&
    echo -e "APP_URL=$DEPLOY_URL" >> .env &&
    echo -e "JOCKO_API_URL=$JOCKO_API_URL" >> .env &&
    echo -e "JOCKO_API_TOKEN=$JOCKO_API_TOKEN" >> .env &&
    cat .env &&
    php artisan key:generate &&
    php artisan export
'''
environment = { PHP_VERSION = "8.1" }
